import os
import unittest
from tempfile import TemporaryDirectory

from nodes.storyboard_store import StoryboardStore


class StoryboardCustomExtensionsTest(unittest.TestCase):
    def build_demo_board(self, board_id="dummy_smoke"):
        return {
            "board_id": board_id,
            "items": [
                {
                    "id": "frame_main",
                    "type": "frame",
                    "x": 0,
                    "y": 0,
                    "w": 1560,
                    "h": 2260,
                    "label": "Dummy Zone",
                    "color": "#ffffff",
                    "frame_presentation": "board",
                },
                {
                    "id": "mood_1",
                    "type": "mood_tag",
                    "x": 48,
                    "y": 70,
                    "w": 220,
                    "h": 92,
                    "label": "Quiet Tension",
                    "content": "Soft light and held breath.",
                    "accent": "#d6e4ff",
                },
                {
                    "id": "prompt_1",
                    "type": "prompt_card",
                    "x": 80,
                    "y": 204,
                    "w": 308,
                    "h": 196,
                    "label": "Storm rooftop prompt",
                    "prompt_text": "cinematic rooftop at night, wind-torn coat, sodium haze, moody practicals, tense atmosphere",
                    "content": "Pushes a curated prompt fragment into the board prompt bar.",
                    "accent": "#c7f9cc",
                },
                {
                    "id": "shot_1",
                    "type": "shot_card",
                    "x": 300,
                    "y": 70,
                    "w": 272,
                    "h": 176,
                    "label": "Opening Reveal",
                    "shot_type": "Wide",
                    "content": "Begin wide, then let the subject puncture the frame.",
                    "accent": "#fde68a",
                },
                {
                    "id": "beat_1",
                    "type": "story_beat",
                    "x": 600,
                    "y": 70,
                    "w": 268,
                    "h": 168,
                    "label": "The world shifts",
                    "beat_stage": "Conflict",
                    "content": "Reference images become sequential beats.",
                    "accent": "#c7f9cc",
                },
                {
                    "id": "swatch_1",
                    "type": "swatch_strip",
                    "x": 80,
                    "y": 320,
                    "w": 308,
                    "h": 136,
                    "label": "Base Palette",
                    "content": "Stone, canvas, fog, graphite",
                    "swatches": ["#f4efe6", "#cab9a5", "#7a8795", "#1f2937"],
                },
                {
                    "id": "divider_1",
                    "type": "scene_divider",
                    "x": 460,
                    "y": 68,
                    "w": 380,
                    "h": 86,
                    "label": "Sequence Two",
                    "content": "Night interiors",
                    "accent": "#bfdbfe",
                },
                {
                    "id": "character_1",
                    "type": "character_card",
                    "x": 430,
                    "y": 320,
                    "w": 272,
                    "h": 196,
                    "label": "Ari Vale",
                    "character_role": "Lead",
                    "look": "Weathered coat, silver ring, tired eyes",
                    "content": "Reserved but vigilant. Every glance feels preloaded.",
                    "accent": "#e2e8f0",
                },
                {
                    "id": "location_1",
                    "type": "location_card",
                    "x": 876,
                    "y": 118,
                    "w": 244,
                    "h": 176,
                    "label": "Harbor Rooftop",
                    "time_of_day": "Night",
                    "content": "Wet concrete, sodium haze, wind pushing loose fabric.",
                    "accent": "#bfdbfe",
                },
                {
                    "id": "lens_1",
                    "type": "lens_card",
                    "x": 1150,
                    "y": 118,
                    "w": 256,
                    "h": 182,
                    "label": "50mm close tension",
                    "lens_family": "Prime",
                    "focal_length": "50mm T2",
                    "coverage": "Compressed shoulder-up with slight parallax",
                    "content": "Keep the falloff gentle so the background still breathes.",
                    "accent": "#e2e8f0",
                },
                {
                    "id": "dialogue_1",
                    "type": "dialogue_card",
                    "x": 732,
                    "y": 352,
                    "w": 388,
                    "h": 154,
                    "label": "Mara",
                    "line_text": "If we wait for it to feel safe, we stay here forever.",
                    "delivery": "Measured",
                    "accent": "#fde68a",
                },
                {
                    "id": "wardrobe_1",
                    "type": "wardrobe_card",
                    "x": 430,
                    "y": 546,
                    "w": 272,
                    "h": 188,
                    "label": "Harbor Coat",
                    "wardrobe_priority": "Hero",
                    "silhouette": "Long coat, sharp shoulder, worn hem, hidden inner pocket.",
                    "palette_note": "Stone, charcoal, salt-faded blue",
                    "content": "Fabric should hold shape in the wind without looking stiff.",
                    "accent": "#e2e8f0",
                },
                {
                    "id": "set_dressing_1",
                    "type": "set_dressing_card",
                    "x": 80,
                    "y": 490,
                    "w": 308,
                    "h": 186,
                    "label": "Rooftop utility clutter",
                    "dressing_zone": "Foreground",
                    "texture_stack": "Wet tarp, milk crate, rusted chain, old lantern glass",
                    "content": "Give the foreground one object that catches light and one that swallows it.",
                    "accent": "#c7f9cc",
                },
                {
                    "id": "checklist_1",
                    "type": "checklist_card",
                    "x": 430,
                    "y": 770,
                    "w": 272,
                    "h": 220,
                    "label": "Shot Readiness",
                    "checklist_items": [
                        {"done": True, "label": "Frame selected"},
                        {"done": False, "label": "Lighting matched"},
                        {"done": False, "label": "Prop checked"},
                        {"done": True, "label": "Prompt ready"},
                    ],
                    "checklist_text": "[x] Frame selected\n[ ] Lighting matched\n[ ] Prop checked\n[x] Prompt ready",
                    "content": "Track what is truly ready before moving on.",
                    "accent": "#bfdbfe",
                },
                {
                    "id": "hair_makeup_1",
                    "type": "hair_makeup_note",
                    "x": 732,
                    "y": 538,
                    "w": 388,
                    "h": 176,
                    "label": "Wind-broken fringe and cold skin",
                    "hmu_area": "Hair",
                    "application": "Loose flyaways, slight temple dampness, lip tone pulled cooler",
                    "content": "The look should feel like the air changed her before the scene did.",
                    "accent": "#fde68a",
                },
                {
                    "id": "move_1",
                    "type": "camera_move",
                    "x": 732,
                    "y": 748,
                    "w": 388,
                    "h": 100,
                    "label": "Reveal the subject as the wind shifts",
                    "move_type": "Push In",
                    "duration": "4 beats",
                    "content": "Stay gentle and deliberate. Let the frame settle before the face lands.",
                    "accent": "#c7f9cc",
                },
                {
                    "id": "light_1",
                    "type": "lighting_cue",
                    "x": 1150,
                    "y": 334,
                    "w": 256,
                    "h": 172,
                    "label": "Cool window spill",
                    "lighting_style": "Soft Key",
                    "source": "Window left + sodium practical in the distance",
                    "content": "Keep one cheek in shadow so the face never goes fully comfortable.",
                    "accent": "#bfdbfe",
                },
                {
                    "id": "continuity_1",
                    "type": "continuity_note",
                    "x": 1150,
                    "y": 538,
                    "w": 256,
                    "h": 166,
                    "label": "Left hand stays on railing",
                    "continuity_type": "Hand Position",
                    "checkpoint": "Carry across wide, over-shoulder, and insert",
                    "content": "Match finger spacing before the cut so the gesture lands as one continuous beat.",
                    "accent": "#fde68a",
                },
                {
                    "id": "stunt_1",
                    "type": "stunt_note",
                    "x": 80,
                    "y": 1162,
                    "w": 308,
                    "h": 176,
                    "label": "Controlled slip into railing catch",
                    "stunt_level": "Coordination",
                    "rigging": "Hidden knee pads, soft edge on rail, reset mark taped camera side",
                    "content": "The move should feel accidental on camera but precise for the performer.",
                    "accent": "#fde68a",
                },
                {
                    "id": "prop_1",
                    "type": "prop_card",
                    "x": 1150,
                    "y": 736,
                    "w": 256,
                    "h": 164,
                    "label": "Silver ring",
                    "prop_state": "Hero Prop",
                    "content": "Cold metal, worn edges, catches a clean highlight when the hand turns.",
                    "accent": "#e2e8f0",
                },
                {
                    "id": "sound_1",
                    "type": "sound_cue",
                    "x": 732,
                    "y": 700,
                    "w": 388,
                    "h": 132,
                    "label": "Ferry horn underneath",
                    "sound_type": "Ambience",
                    "content": "Bring it in before the cut so the location arrives early.",
                    "accent": "#fde68a",
                },
                {
                    "id": "transition_1",
                    "type": "transition_card",
                    "x": 1150,
                    "y": 934,
                    "w": 256,
                    "h": 118,
                    "label": "Hand closes to door latch",
                    "transition_type": "Match Cut",
                    "content": "Use shape continuity so the edit feels inevitable, not flashy.",
                    "accent": "#c7f9cc",
                },
                {
                    "id": "editorial_1",
                    "type": "editorial_card",
                    "x": 1150,
                    "y": 1086,
                    "w": 256,
                    "h": 152,
                    "label": "Hold one beat after the glance",
                    "edit_rhythm": "Hold",
                    "cut_logic": "Let the look finish before the cut steals the tension",
                    "content": "The pause should feel intentional, not slow.",
                    "accent": "#bfdbfe",
                },
                {
                    "id": "production_1",
                    "type": "production_note",
                    "x": 430,
                    "y": 1234,
                    "w": 272,
                    "h": 170,
                    "label": "Access rooftop one hour before dusk",
                    "production_department": "Locations",
                    "status": "Confirm elevator key + rain cover",
                    "content": "Build setup time into the board so the mood references stay achievable.",
                    "accent": "#e2e8f0",
                },
                {
                    "id": "vfx_1",
                    "type": "vfx_note",
                    "x": 732,
                    "y": 882,
                    "w": 388,
                    "h": 156,
                    "label": "Remove rooftop safety wire",
                    "vfx_task": "Cleanup",
                    "plate_status": "Plate locked, track marker hidden in shadow",
                    "content": "Keep the skyline honest. Cleanup should disappear before the eye gets there.",
                    "accent": "#bfdbfe",
                },
                {
                    "id": "graphics_1",
                    "type": "graphics_note",
                    "x": 732,
                    "y": 1274,
                    "w": 388,
                    "h": 164,
                    "label": "Phone UI needs storm warning banner",
                    "graphic_type": "Screen Insert",
                    "placement": "Upper third, slight lens warp, brightness below face key",
                    "content": "The graphic should support urgency without becoming the brightest point in frame.",
                    "accent": "#c7f9cc",
                },
                {
                    "id": "grade_1",
                    "type": "grade_card",
                    "x": 1150,
                    "y": 1124,
                    "w": 256,
                    "h": 180,
                    "label": "Night steel with gentle skin separation",
                    "grade_direction": "Silver Blue",
                    "palette_note": "Blue steel mids, pale highlights, restrained amber practicals",
                    "content": "Keep faces readable without letting the board drift into clean commercial contrast.",
                    "accent": "#bfdbfe",
                },
                {
                    "id": "basket_1",
                    "type": "reference_basket",
                    "x": 430,
                    "y": 1438,
                    "w": 272,
                    "h": 190,
                    "label": "Saved Reference Group",
                    "linked_ids": ["mood_1", "shot_1", "light_1", "grade_1"],
                    "content": "Capture the current selection, then reselect it later with one click.",
                    "accent": "#fde68a",
                },
                {
                    "id": "blocking_1",
                    "type": "blocking_note",
                    "x": 430,
                    "y": 1112,
                    "w": 690,
                    "h": 170,
                    "label": "Mara crosses foreground before reveal",
                    "blocking_pattern": "Cross Left",
                    "staging": "Start framed by door edge, then cut across lens line before settling on mark.",
                    "content": "Keep the move soft enough that the audience feels the reveal before they fully see it.",
                    "accent": "#c7f9cc",
                },
            ],
            "selection": [],
            "settings": {},
        }

    def test_render_board_preview_supports_custom_extension_items(self):
        with TemporaryDirectory() as tmp:
            store = StoryboardStore(tmp)
            board = self.build_demo_board()
            store.save_board(board, notify=False)

            preview = store.render_board_preview(board["board_id"], scale=1.0)

            self.assertIsNotNone(preview)
            self.assertGreater(preview.size[0], 0)
            self.assertGreater(preview.size[1], 0)

    def test_flatten_frame_creates_assets_dir_for_layout_only_board(self):
        with TemporaryDirectory() as tmp:
            store = StoryboardStore(tmp)
            board = self.build_demo_board()
            store.save_board(board, notify=False)

            flattened_name = store.flatten_frame(board["board_id"], "frame_main", scale=1.0)

            self.assertTrue(flattened_name)
            flattened_path = os.path.join(store._get_assets_path(board["board_id"]), flattened_name)
            self.assertTrue(os.path.exists(flattened_path))


if __name__ == "__main__":
    unittest.main()
